name: Package release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet 2.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'

      - name: Setup dotnet 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Setup dotnet 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}

      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
 
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output nupkgs

      - name: Push
        run: dotnet nuget push nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}